version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development 
    volumes:
      - ./app:/usr/src/app 
    command: sh -c "npm run start"
    ports:
      - "8888:8080"
    tty: true
